spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/closetalk
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'closetalk_admin'
    password: 'rladlarladlsk1212'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: file:media/,classpath:/static

#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
