spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    redis:
      port: '${REDIS_PORT}'  #Redis 기본 포트 번호
      host: '${REDIS_HOST}' #로컬 테스트에서는 localhost, 배포시에는 redis(redis 환경변수)
      password: '${REDIS_PASSWORD}'

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 120MB

  mvc:
    static-path-pattern: "/static/**"
    hidden-method:
      filter:
        enabled: true

  web:
    resources:
      static-locations: file:media/,classpath:/static


  #소셜 로그인 관련 yaml 설정
  security:
    oauth2:
      client:
        #서비스 제공자
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        #서비스 사용을 위한 클라이언트 식별 정보(api 사용 허가 받은 정보)
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI}
            scope:
              - nickname
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
  mail:
    host: smtp.naver.com                #네이버: smtp.naver.com
    port: 465                           #네이버 설정에 포트는 모바일 메일 포트인 듯. PC서비스에서는 465
    username: ${MAIL_USERNAME}         #네이버 이메일 주소
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.trust: smtp.naver.com   #호스트와 동일하게
      mail.smtp.starttls.enable: true
