
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/closetalk
    username: 'closetalk_admin'
    password: 'rladlarladlsk1212'

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

    hibernate:
      ddl-auto: create