
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/closetalk
    username: 'closetalk_admin'
    password: 'rladlarladlsk1212'

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

jwt:
  secret: p0s+ooKbS4Z8Wcx0BkGJiLEOwyC34f1mLapC4swTT5Y=