spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/closetalk
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'closetalk_admin'
    password: 'rladlarladlsk1212'
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  #  sql:
  #    init:
  #      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    static-path-pattern: "/static/**"
    hiddenmethod:
      filter:
        enabled: true

  web:
    resources:
      static-locations: file:media/,classpath:/static

  #소셜 로그인 관련 yaml 설정
  security:
    oauth2:
      client:
        #서비스 제공자
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        #서비스 사용을 위한 클라이언트 식별 정보(api 사용 허가 받은 정보)
        registration:
          naver:
            client-id: username
            client-secret: password
            client-name: naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - nickname
              - email
          kakao:
            client-id: username
            client-secret: password
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email

jwt:
  secret : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c