spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/closetalk
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'closetalk_admin'
    password: 'rladlarladlsk1212'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: file:issue/,classpath:/static

file:
  upload-dir=/Users/KYS/git/Project_Closetalk/src/main/resources/static/images/issue
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
